### ISSUE TITLE
HDF5 bugs

### ISSUE THREAD

**Issue by Chrede88** [folk-lab/IgorAcq#67]
1) The scan comment doesn't make it into the HDF5 file. The local variable is called `msg`.  
2) The `xdata` array have `size=1`, if `readvstime=1`.

**Comment by nikhartman** [comment]
I totally know how to fix these. Should have time tomorrow.

**Comment by Chrede88** [comment]
I just fixed it. see #68

**Comment by nikhartman** [comment]
The `comment` is still buggy. I keep seeing `[WARNING] Value does not fit any JSON type:  the scan was aborted during the execution.`.

**Comment by nikhartman** [comment]
See #69
